---
pipeline: 2018_05_30_ResistanceMechanisms_Kapoor
workspace_dir: /home/ubuntu/bucket/projects/2018_05_30_ResistanceMechanisms_Kapoor/workspace
output_dir: profiles
sc_output_dir: sc_profiles
platemap_well_column: Metadata_well_position
single_cell:
  perform: true
  normalize: true
  feature_select: true
aggregate:
  perform: true
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  features: infer
count:
  perform: true
  output_dir: cell_counts
annotate:
  perform: true
  well_column: Metadata_Well
normalize:
  perform: true
  method: standardize
  features: infer
feature_select:
  perform: true
  features: infer
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
    - drop_outliers
options:
  compression: gzip
  sc_float_format: "%.5g"
  samples: all
---
batch: 2019_02_15_Batch1_20X
plates:
  - HCT116bortezomib
process: false
process_single_cell: false
---
batch: 2019_02_15_Batch1_40X
plates:
  - HCT116bortezomib
process: false
process_single_cell: false
---
batch: 2019_03_20_Batch2
plates:
  - 207106_exposure320
process: false
process_single_cell: true
---
batch: 2019_06_25_Batch3
plates:
  - WTClones
  - MutClones
process: false
process_single_cell: false
---
batch: 2019_11_11_Batch4
plates:
  - WTmut04hWed
  - WTmut04hTh
process: false
process_single_cell: false
---
batch: 2019_11_19_Batch5
plates:
  - 217755
process: false
process_single_cell: false
---
batch: 2019_11_20_Batch6
plates:
  - 217760
  - 217762
process: false
process_single_cell: false
---
batch: 2019_11_22_Batch7
plates:
  - 217766
  - 217768
process: false
process_single_cell: false
---
batch: 2020_07_02_Batch8
plates:
  - 218360
  - 218361
  - 218362
  - 218363
process: false
process_single_cell: false
---
batch: 2020_08_24_Batch9
plates:
  - 218696
  - 218697
  - 218698
  - 218699
  - 218774
  - 218775
process: false
process_single_cell: false
---
batch: 2020_09_08_Batch10
plates:
  - 218852
  - 218853
  - 218854
  - 218855
  - 218856
  - 218857
  - 218858
  - 218859
process: false
process_single_cell: false
---
batch: 2021_02_08_Batch11
plates:
  - 219814
process: true
process_single_cell: true
